no=eval(input("enter number between 1 to 12"))
if no==1:
    print(no ,'january')
if no==2:
    print(no ,'february')
if no==3:
    print(no ,'March')
if no==4:
    print(no ,'april')
if no==5:
    print(no ,'may')
if no==6:
    print(no ,'june')
if no==7:
    print(no ,'july')
if no==8:
    print(no ,'august')
if no==9:
    print(no ,'september')
if no==10:
    print(no ,'october')
if no==11:
    print(no ,'november')
if no==12:
    print(no ,'december')
